backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "categories_collection"
    label: "Kategorien"
    files:
      - name: "categories_json_file"
        label: "Kategorien Liste"
        file: "src/data/categories.json"
        fields:
          - { label: "Kategorien", name: "categories", widget: "list", fields: [
              { label: "ID", name: "id", widget: "string" },
              { label: "Name", name: "name", widget: "string" },
              { label: "Slug", name: "slug", widget: "string", required: false },
              { label: "Kurzbeschreibung", name: "short_description", widget: "string", required: false },
              { label: "Bild", name: "image", widget: "image", required: false },
              { label: "Icon", name: "icon", widget: "image", required: false }
            ] }
  - name: "offers_collection"
    label: "Angebote"
    files:
      - name: "offers_json_file"
        label: "Angebote Liste"
        file: "src/data/offers.json"
        fields:
          - { label: "Angebote", name: "offers", widget: "list", fields: [
              { label: "ID", name: "id", widget: "string" },
              { label: "Titel", name: "title", widget: "string" },
              { label: "Beschreibung", name: "description", widget: "string" },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Alter Preis", name: "old_price", widget: "string", required: false },
              { label: "GÃ¼ltig bis", name: "validUntil", widget: "datetime" },
              { label: "Bild", name: "image", widget: "image", required: false },
              { label: "Kategorie", name: "category_id", widget: "string", required: false }
            ] }
